'use strict'

const ADDITIONAL_COLUMNS = ['codes', 'sentiment', 'reviewed', 'changed']
const QUESTION_CATEGORY_CUSTOMER_SATISFACTION = 'CS'
const QUESTION_CATEGORY_EMPLOYEE_FEEDBACK = 'EF'
const QUESTION_CATEGORY_BRAND_PERCEPTION = 'BR'
const QUESTION_CATEGORY_PRODUCT_PERCEPTION = 'PP'
const QUESTION_CATEGORY_EVENT_EVALUATION = 'EV'
const QUESTION_CATEGORY_LIST = 'LA'
const QUESTION_CATEGORY_OTHER = 'OT'
const QUESTION_CATEGORY_NONE = 'NO'

const QUESTION_CATEGORIES = [
  QUESTION_CATEGORY_CUSTOMER_SATISFACTION,
  QUESTION_CATEGORY_EMPLOYEE_FEEDBACK,
  QUESTION_CATEGORY_BRAND_PERCEPTION,
  QUESTION_CATEGORY_PRODUCT_PERCEPTION,
  QUESTION_CATEGORY_EVENT_EVALUATION,
  QUESTION_CATEGORY_LIST,
  QUESTION_CATEGORY_OTHER,
  QUESTION_CATEGORY_NONE
]

const MIN_CODE_LABEL_LEN = 2
const MIN_CODE_CATEGORY_LEN = 2

const UPLOAD_LANGUAGES = ['af', 'bg', 'bs', 'ca', 'cs', 'cy', 'da', 'de', 'el', 'en', 'es', 'et', 'fi', 'fr', 'ga', 'hr', 'hu', 'id', 'it', 'ka', 'lb', 'lt', 'lv', 'mk', 'ml', 'nl', 'no', 'pl', 'pt', 'ro', 'sk', 'sq', 'sr', 'sv', 'tr', 'uk']

// training time estimation: tpu_boot_time + coder_overhead + (nanswers * ncodes) * nepochs / samples_per_sec
const TRAINING_TIME_ESTIMATOR_BERT = (nanswers, ncodes) => 225 + 155 + (nanswers * ncodes) * 5 / 1000

const CHART_TYPE_BAR = 'bar'
const CHART_TYPE_LINE_PIE = 'line-pie'
const CHART_TYPE_TREEMAP = 'treemap'
const CHART_TYPE_GRAPH = 'graph'
const CHART_TYPE_PSEUDO_TEXT = 'p-text'
const CHART_TYPE_PSEUDO_VERBATIMS = 'p-verb'

const CHART_TYPES = [
  CHART_TYPE_BAR,
  CHART_TYPE_LINE_PIE,
  CHART_TYPE_TREEMAP,
  CHART_TYPE_GRAPH,
  CHART_TYPE_PSEUDO_TEXT,
  CHART_TYPE_PSEUDO_VERBATIMS
]

const CHART_TYPES_TO_API_ENUM = {
  'bar': 'BAR',
  'line-pie': 'LINEP',
  'treemap': 'TREE',
  'graph': 'GRAPH',
  'p-text': 'P_TXT',
  'p-verb': 'P_VRB'
}

const DS_SETTINGS_TEMPLATE = { weighting_column: null, weighting_normalize: false, name: '' }
const DS_FILTERS_TEMPLATE = [{ type: 'empty', value: true }]

export {
  MIN_CODE_LABEL_LEN,
  MIN_CODE_CATEGORY_LEN,

  ADDITIONAL_COLUMNS,

  QUESTION_CATEGORIES,
  QUESTION_CATEGORY_CUSTOMER_SATISFACTION,
  QUESTION_CATEGORY_EMPLOYEE_FEEDBACK,
  QUESTION_CATEGORY_BRAND_PERCEPTION,
  QUESTION_CATEGORY_PRODUCT_PERCEPTION,
  QUESTION_CATEGORY_EVENT_EVALUATION,
  QUESTION_CATEGORY_LIST,
  QUESTION_CATEGORY_OTHER,
  QUESTION_CATEGORY_NONE,

  CHART_TYPES,
  CHART_TYPE_BAR,
  CHART_TYPE_LINE_PIE,
  CHART_TYPE_TREEMAP,
  CHART_TYPE_GRAPH,
  CHART_TYPE_PSEUDO_TEXT,
  CHART_TYPE_PSEUDO_VERBATIMS,

  CHART_TYPES_TO_API_ENUM,

  DS_FILTERS_TEMPLATE,
  DS_SETTINGS_TEMPLATE,

  UPLOAD_LANGUAGES,
  TRAINING_TIME_ESTIMATOR_BERT
}
